### ISSUE TITLE
Vimeo Player Parameters

### ISSUE THREAD

**Issue by tortilaman** [robb/jekyll-embedly-client#6]
I'm trying to use this to embed some vimeo videos in my site with custom player parameters from vimeo. I've added them to to config.yml and added a puts to the file to make sure the URL that's being output is corect according to a forum post I've seen. From what I've seen this should be working, but I'm just getting a regular vimeo video and not a configured one.

_Relevant config.yml_

```
embedly:
  api_key: ######################

  vimeo:
    vimeo_color: ff9933
    vimeo_title: 0
    vimeo_byline: 0
    vimeo_portrait: 0
```

_embed.ly url_

```
http://api.embed.ly/1/oembed?key=################&url=https%3A%2F%2Fvimeo.com%2F142537975&vimeo_color=ff9933&vimeo_title=0&vimeo_byline=0&vimeo_portrait=0
```

I'm kind of lost as to why this isn't working, but I'm new to Ruby and embed.ly so I'm probably missing something. I also tried adding the vimeo parameters to the `@@EMBEDLY_PARAMETERS` array, but no dice. Any help would be appreciated.
